### ISSUE TITLE
Wondering where this follow_link_or_create functionality is being provided

### ISSUE THREAD

**Issue by megalithic** [kaile256/dotfiles#5]
https://github.com/kaile256/dotfiles/blob/71198aa0c9ff97ab91182e4791e0384669f2340b/.config/nvim/lua/rc/lsp/config/ls/zk.lua#L36

Hi there @kaile256!

I'm just wondering here the above code usages have been defined/provided. Any pointers would be dope. Thanks!

**Comment by kaile256** [comment]
It is just a broken mapping missing TODO comment for it ;)

Currently, I type `gf`, or `<C-w>f`, to follow links with `:setlocal suffixesadd=.md`, and create notes typing  `zk new` from terminal buffer like an idiot.
